### ISSUE TITLE
Travis failure: Fixture mananger has no open profile

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-plugin-template#10]
Hiya, so I've just made a new repo using the template. I've only replaced the project name and setup.json, as per the instructions, to get to this commit: chrisjsewell/aiida-crystal17@05315ae, but in the Travis tests (here https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/419713155) I get:

```python
======================================================================
ERROR: setUpClass (aiida_crystal17.tests.test_calculations.TestMultiply)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/aiida/utils/fixtures.py", line 439, in setUpClass
    "Fixture mananger has no open profile. Please use aiida.utils.fixtures.TestRunner to run these tests."
ValueError: Fixture mananger has no open profile. Please use aiida.utils.fixtures.TestRunner to run these tests.

```

Is this something I've done wrong (probably), or a bug?

Thanks in advance, Chris

**Comment by ltalirz** [comment]
Hi Chris, I will look into this lateron, but in the meanwhile - I actually want to replace the plugin template by the plugin cutter here: https://github.com/aiidateam/aiida-plugin-cutter

Since I've worked on it lateron, it might already have addressed this issue, perhaps worth having a look

**Comment by chrisjsewell** [comment]
Thanks for the quick response. I've updated my repo to the plugin cutter template, but I still get the same error: https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/419744236

**Comment by chrisjsewell** [comment]
BTW (not related to this issue), but would it not be easier to source the version directly from the project, rather than specifying it in `setup.json` and doing the version check:

```python
#!/usr/bin/env python

from setuptools import setup, find_packages
from importlib import import_module
import json

if __name__ == '__main__':
    # Provide static information in setup.json
    # such that it can be discovered automatically
    with open('setup.json', 'r') as info:
        kwargs = json.load(info)
    setup(
        packages=find_packages(),
        version=import_module('aiida_crystal17').__version__,
        long_description=open('README.md').read(),
        long_description_content_type='text/markdown',
        **kwargs)
```

**Comment by ltalirz** [comment]
> BTW (not related to this issue), but would it not be easier to source the version directly from the project, rather than specifying it in setup.json and doing the version check

Unfortunately we currently need the version number in both places, since the `setup.json` is read by the [AiiDA plugin registry](https://aiidateam.github.io/aiida-registry/).

**Comment by chrisjsewell** [comment]
Ah fair point

**Comment by ltalirz** [comment]
> I've updated my repo to the plugin cutter template, but I still get the same error: https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/419744236

Ah yes - when using `unittest`, the complex setup for the test fixtures does not allow us to use the simple `python -m unittest discover`. You need to use [`manage.py`](https://github.com/aiidateam/aiida-plugin-cutter/blob/master/%7B%7Bcookiecutter.plugin_name%7D%7D/manage.py)
I'm puzzled as to why this was not yet set up in the plugin cutter - I will have a look.

**Comment by chrisjsewell** [comment]
As long as it wasn't me being stupid lol! I've always used `pytest`, so not as knowledgeable with `unittest`. Do I just replace `python -m unittest discover` with `python manage.py` then?

**Comment by ltalirz** [comment]
> As long as it wasn't me being stupid lol! I've always used `pytest`, so not as knowledgeable with `unittest`. Do I just replace `python -m unittest discover` with `python manage.py` then? 

Yes. But you can also just use the pytest fixtures, which don't suffer from this problem
https://github.com/aiidateam/aiida_core/blob/dddfffc459532dffca9df9426e2dc894fa19c94c/aiida/utils/fixtures.py#L89

**Comment by chrisjsewell** [comment]
even better

**Comment by chrisjsewell** [comment]
Ok getting somewhere; https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/419795868, I get:

```python
FixtureError: 'AiiDA dbenv can not be loaded while creating a test profile'
```

**Comment by ltalirz** [comment]
'unittest' issue fixed by https://github.com/aiidateam/aiida-plugin-cutter/pull/4
Let's continue the `pytest` discussion [here](https://github.com/aiidateam/aiida-plugin-cutter/issues/10)
