### ISSUE TITLE
create pypi package

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-template#2]
So that you can do `pip install aiida-plugin-template`

**Comment by dev-zero** [comment]
why would you want to do that?

**Comment by ltalirz** [comment]
It's a minimal aiida plugin that should, supposedly, always work (e.g. if you want to test whether installing plugins is broken).
I see no reason not to do it.

**Comment by dev-zero** [comment]
ah, so you basically replace the "aiida-mul" plugin

**Comment by ltalirz** [comment]
exactly, aiida-mul should go.

**Comment by ltalirz** [comment]
done https://pypi.python.org/pypi/aiida-plugin-template/0.2.0
