### ISSUE TITLE
should we include automatic version updating from git tags?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-template#5]
DropD wrote a script that reads the git tags to automatically update plugin version numbers in the respective places

https://github.com/DropD/aiida-vasp/blob/f853735e23755254a29411c240c726c38a9f3dbb/ops/update_version.py#L26-L60

https://github.com/DropD/aiida-vasp/blob/f853735e23755254a29411c240c726c38a9f3dbb/.pre-commit-config.yaml#L22-L26

Should we include this in the aiida-plugin-template?

Pro:
 * out-of-date version numbers is an issue most plugin developers are likely to run into at some point. this solves that issue

Neutral:
 * forces people to use git tags for versioning

Con:
 * adds another file to the "minimal template"

**Comment by giovannipizzi** [comment]
I've done a different approach in the quantum espresso plugin: just a precommit hook to check the version numbers and that they match: https://github.com/aiidateam/aiida-quantumespresso/blob/develop/.travis-data/precommit/fix_setup_version.py 

I'm not fully sure I understand how the approach implemented by @DropD would work in a real scenario - i.e., in which order should I create a commit and tag it when I want to do a release. (And how this integrates with github+travis+protected branches)

I thought it was easier to let the user decide, but of course I'm open to different approaches. Anyway, I think that something simple should be added to the template, especially if it does not need to be adapted by the user.

**Comment by ltalirz** [comment]
I'll let @DropD answer regarding the questions.

In general I find @giovannipizzi's approach a bit less intrusive and it doesn't force users to use git tags for versioning. Of course, the user then still needs to take care of updating the version number when making a release.

As for the location of the file, I think it's very reasonable to put it into a dot-prefix directory - users who don't care about it shouldn't see it. Could be `.pre-commit/` instead of `.travis-data`, but that's details...

**Comment by DropD** [comment]
In practice it works as follows:

Changing the version:
1. tag the commit
1. run pre-commit (or change both version numbers by hand)
1. add changes, commit and push (including the tag)

Safety checks
* If you change version numbers without tagging, travis build will fail
* If you tag without changing version numbers travis build will fail
* If you have not tags at all, travis build will fail

I think we should not provide this as the default behaviour but maybe link to a snippet for people who would like to use git tag based versioning / as an example for a custom hook.

**Comment by DropD** [comment]
The only thing i prefer over the solution in quantumespresso is that the version numbers get changed for you instead of simply failing the pre-commit run. 

That would not be hard to do though.

**Comment by ltalirz** [comment]
For the moment, we will just do the check.
See https://github.com/ltalirz/aiida-diff/blob/master/.travis-data/check_version.py
